# Workflow name 
name : "Actions Workflow"

# workflow event
on: [push]

# for each events there can be one or more jobs 
jobs:
  # key pair value  <job name> : <steps>
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name : Echo a string
        run : echo "Hello World"
      - name: Multiline script
        run : |
          node -v
          npm -v
        shell: bash
        

  
  